# Generated by Django 3.2.2 on 2022-01-06 10:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_branch',
            fields=[
                ('br_id', models.AutoField(primary_key=True, serialize=False)),
                ('br_name', models.CharField(max_length=300)),
                ('br_pin', models.CharField(max_length=100, null=True)),
                ('br_country', models.CharField(max_length=200)),
                ('br_vat', models.CharField(max_length=300, null=True)),
                ('br_gst', models.CharField(max_length=200, null=True)),
                ('br_email', models.EmailField(max_length=300)),
                ('br_phone', models.BigIntegerField()),
                ('br_address', models.CharField(max_length=300, null=True)),
                ('br_city', models.CharField(max_length=200, null=True)),
                ('br_state', models.CharField(max_length=200)),
                ('br_description', models.TextField(max_length=600)),
                ('br_date', models.DateTimeField(auto_now_add=True)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_join_date', models.DateTimeField(auto_now=True)),
                ('cus_name', models.CharField(max_length=300, null=True)),
                ('cus_email', models.EmailField(max_length=300, null=True)),
                ('cus_mobile', phone_field.models.PhoneField(max_length=31, null=True)),
                ('cus_address', models.TextField(null=True)),
                ('cus_loyalty', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_company', models.CharField(max_length=200)),
                ('sup_pin', models.CharField(max_length=200, null=True)),
                ('sup_name', models.CharField(max_length=500, null=True)),
                ('sup_country', models.CharField(max_length=200, null=True)),
                ('sup_vat', models.CharField(max_length=300, null=True)),
                ('sup_gst', models.CharField(max_length=200, null=True)),
                ('sup_email', models.EmailField(max_length=300)),
                ('sup_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('sup_address', models.CharField(max_length=300, null=True)),
                ('sup_city', models.CharField(max_length=200, null=True)),
                ('sup_state', models.CharField(max_length=300, null=True)),
                ('sup_description', models.CharField(max_length=600, null=True)),
                ('sup_date', models.DateTimeField(auto_now_add=True)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('us_name', models.CharField(max_length=300)),
                ('us_email', models.EmailField(max_length=300)),
                ('us_password', models.CharField(max_length=300)),
                ('us_type', models.CharField(max_length=100)),
                ('us_phone', phone_field.models.PhoneField(max_length=31, null=True)),
                ('us_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('company', models.IntegerField(null=True)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user_types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(max_length=250)),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_warehouse',
            fields=[
                ('wr_id', models.AutoField(primary_key=True, serialize=False)),
                ('wr_name', models.CharField(max_length=300, null=True)),
                ('wr_address', models.TextField(null=True)),
                ('wr_building', models.CharField(max_length=100, null=True)),
                ('wr_description', models.TextField(null=True)),
                ('wr_image', models.ImageField(blank=True, null=True, upload_to='warehouses')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trash', models.BooleanField(default=True)),
            ],
        ),
    ]
